/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.qq120011676.nfptj;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class NFPTJTest {
    @Test
    void applyTokenTest() {
        String userId = "1158";
        String password = "bwzppo7yj4";
        String publicKey = "3059301306072a8648ce3d020106082a811ccf5501822d03420004f228e9d80fe12e628d9e8106d9a6c236eaa63d00ae47888bc3217ceb7002953cd458eccbdc6f75aacb9c21e84689b6b0b9b2d79b9c96efeba5dca2e9998873ce";
        String baseUrl = "http://218.67.246.252:6999";
        NFPTJ nfptj = new NFPTJ(userId, password, publicKey, baseUrl);
        Assertions.assertNotNull(nfptj.applyToken(), "测试获取令牌接口失败");
    }
}
