/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.qq120011676.nfptj;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
